/**
 * Przebudowa bazy cytatów – tylko PRAWDZIWE cytaty (wypowiedzi lub powszechnie przypisywane zdania),
 * bez tytułów dzieł, haseł typu "X – opis" ani opisów. Odpowiedź zawsze: imię i nazwisko (lub jasna atrybucja).
 */
const fs = require("fs");
const path = require("path");

const quotes = [
  { quote: "Jam nie z soli ani z roli, jeno z tego, co mnie boli.", answer: "Stefan Czarniecki", context: "XVII w.", grades: [4, 6] },
  { quote: "Nie oddamy ani guzika.", answer: "Józef Beck", context: "Przed II wojną światową.", grades: [4, 8] },
  { quote: "Nie lękajcie się!", answer: "Jan Paweł II", context: "Inauguracja pontyfikatu 1978.", grades: [4, 8] },
  { quote: "Polska nie zginęła, póki my żyjemy.", answer: "Józef Wybicki", context: "Mazurek Dąbrowskiego.", grades: [4, 6] },
  { quote: "Za króla Sasa jedz, pij i popuszczaj pasa.", answer: "Szlachta polska", context: "Czasy saskie.", grades: [6] },
  { quote: "Wolność wasza jest wolnością naszą.", answer: "Lech Wałęsa", context: "Kongres USA 1989.", grades: [4, 8] },
  { quote: "Jeszcze Polska nie zginęła.", answer: "Józef Wybicki", context: "Pieśń Legionów.", grades: [4, 6] },
  { quote: "Państwo to ja.", answer: "Ludwik XIV", context: "Król Francji.", grades: [4, 6] },
  { quote: "Veni, vidi, vici.", answer: "Juliusz Cezar", context: "Po bitwie pod Zelą.", grades: [5] },
  { quote: "Wiem, że nic nie wiem.", answer: "Sokrates", context: "Starożytna Grecja.", grades: [5] },
  { quote: "Nie będę bił w braci.", answer: "Bolesław Krzywousty", context: "Testament.", grades: [5] },
  { quote: "Zastałem Polskę drewnianą, zostawiam murowaną.", answer: "Kazimierz Wielki", context: "XIV w.", grades: [4, 5] },
  { quote: "Nic dwa razy się nie zdarza.", answer: "Wisława Szymborska", context: "Wiersz.", grades: [8] },
  { quote: "Człowiek jest człowiekowi wilkiem.", answer: "Thomas Hobbes", context: "Lewiatan.", grades: [6] },
  { quote: "Myślę, więc jestem.", answer: "Kartezjusz", context: "Cogito ergo sum.", grades: [6] },
  { quote: "Nie ma drogi na skróty do prawdziwej wiedzy.", answer: "Maria Skłodowska-Curie", context: "Noblistka.", grades: [4, 7] },
  { quote: "Być zwyciężonym i nie ulec to zwycięstwo.", answer: "Józef Piłsudski", context: "XX w.", grades: [4, 7, 8] },
  { quote: "Powiedzcie babci, że zachowałam się jak trzeba.", answer: "Danuta Siedzikówna", context: "Ostatnie słowa „Inki”.", grades: [4, 8] },
  { quote: "Nie chciejcie ojczyzny, która was nic nie kosztuje.", answer: "Jan Paweł II", context: "Warszawa 1979.", grades: [4, 8] },
  { quote: "Solidarność – jeden za wszystkich, wszyscy za jednego.", answer: "Lech Wałęsa", context: "NSZZ Solidarność.", grades: [4, 8] },
  { quote: "Nie pragnij niczego, czego byś nie mógł pragnąć jawnie.", answer: "Epikur", context: "Starożytna Grecja.", grades: [5] },
  { quote: "Daj mi punkt oparcia, a poruszę Ziemię.", answer: "Archimedes", context: "Starożytność.", grades: [5] },
  { quote: "E pur si muove.", answer: "Galileusz", context: "A jednak się kręci – po procesie.", grades: [5, 6] },
  { quote: "Wstrzymał Słońce, ruszył Ziemię.", answer: "Jan Kochanowski", context: "O Koperniku.", grades: [5, 6] },
  { quote: "Tu się bijemy, tu się bronimy.", answer: "Augustyn Kordecki", context: "Obrona Jasnej Góry.", grades: [4, 6] },
  { quote: "Wolność, równość, braterstwo.", answer: "Maximilien Robespierre", context: "Rewolucja francuska.", grades: [6] },
  { quote: "Wojna to kontynuacja polityki innymi środkami.", answer: "Carl von Clausewitz", context: "XIX w.", grades: [7] },
  { quote: "Proletariusze wszystkich krajów, łączcie się!", answer: "Karol Marx", context: "Manifest komunistyczny.", grades: [7] },
  { quote: "Polacy nie gęsi, swój język mają.", answer: "Mikołaj Rej", context: "Renesans.", grades: [5, 6] },
  { quote: "Litwo, ojczyzno moja!", answer: "Adam Mickiewicz", context: "Pan Tadeusz.", grades: [7] },
  { quote: "Miej serce i patrz w serce.", answer: "Adam Mickiewicz", context: "Dziady.", grades: [7] },
  { quote: "Gdybym miał dziesięć rąk, wszystkie by były uzbrojone.", answer: "Tadeusz Kościuszko", context: "Insurekcja 1794.", grades: [4, 6] },
  { quote: "Żeby Polska była Polską.", answer: "Jan Pietrzak", context: "Piosenka, stan wojenny.", grades: [8] },
  { quote: "Nie ma wolności bez Solidarności.", answer: "Lech Wałęsa", context: "Lata 80.", grades: [8] },
  { quote: "Prawdziwy pokój to nie brak wojny.", answer: "Jan Paweł II", context: "Encykliki.", grades: [8] },
  { quote: "Idźcie na cały świat i głoście Ewangelię.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Oddajcie cesarzowi, co cesarskie.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Kościół jest w potrzebie obrony.", answer: "Augustyn Kordecki", context: "Listy z Jasnej Góry.", grades: [6] },
  { quote: "Wolność nie jest dana raz na zawsze.", answer: "Jan Paweł II", context: "Homilie.", grades: [8] },
  { quote: "Nie ma sprawy ważniejszej niż Polska.", answer: "Wincenty Witos", context: "Premier II RP.", grades: [7, 8] },
  { quote: "Żołnierz polski walczy o wolność wielu narodów.", answer: "Władysław Sikorski", context: "II wojna światowa.", grades: [8] },
  { quote: "Zginę za Polskę.", answer: "Witold Pilecki", context: "Ostatnie słowa przed egzekucją.", grades: [4, 8] },
  { quote: "Naród, który traci pamięć, traci sumienie.", answer: "Cyprian Kamil Norwid", context: "XIX w.", grades: [7] },
  { quote: "Ojczyzna to wielki zbiorowy obowiązek.", answer: "Cyprian Kamil Norwid", context: "XIX w.", grades: [7] },
  { quote: "Ku wolności wyswobodził was Chrystus.", answer: "Św. Paweł", context: "List do Galatów.", grades: [5] },
  { quote: "Kto nie był w Warszawie w czasie powstania, nie wie, co to znaczy walka.", answer: "Tadeusz Bór-Komorowski", context: "Powstanie warszawskie.", grades: [8] },
  { quote: "Żądamy chleba i wolności.", answer: "Robotnicy Poznania", context: "Poznański czerwiec 1956.", grades: [8] },
  { quote: "Nie ma lekko.", answer: "Edward Gierek", context: "Odpowiedź na strajki.", grades: [8] },
  { quote: "Pomożecie?", answer: "Edward Gierek", context: "Do robotników 1971.", grades: [8] },
  { quote: "Człowiek rodzi się wolny.", answer: "Jean-Jacques Rousseau", context: "Umowa społeczna.", grades: [6] },
  { quote: "Władza deprawuje, władza absolutna deprawuje absolutnie.", answer: "Lord Acton", context: "XIX w.", grades: [7] },
  { quote: "Rząd ludu, przez lud, dla ludu.", answer: "Abraham Lincoln", context: "Gettysburg.", grades: [6, 7] },
  { quote: "Give me liberty or give me death.", answer: "Patrick Henry", context: "USA, rewolucja.", grades: [6] },
  { quote: "Żelazem i krwią.", answer: "Otto von Bismarck", context: "Zjednoczenie Niemiec.", grades: [7] },
  { quote: "Pokój za wszelką cenę.", answer: "Neville Chamberlain", context: "Przed II wojną.", grades: [8] },
  { quote: "Nigdy w dziejach konfliktów tak wielu nie zawdzięczało tak wiele tak nielicznym.", answer: "Winston Churchill", context: "Bitwa o Anglię.", grades: [8] },
  { quote: "To jest ich najwspanialsza godzina.", answer: "Winston Churchill", context: "II wojna światowa.", grades: [8] },
  { quote: "Od Szczecina nad Bałtykiem po Triest nad Adriatykiem opadła żelazna kurtyna.", answer: "Winston Churchill", context: "Fulton 1946.", grades: [8] },
  { quote: "Jedna śmierć to tragedia, milion to statystyka.", answer: "Józef Stalin", context: "Przypisywane.", grades: [8] },
  { quote: "Wojna to piekło.", answer: "William Sherman", context: "Wojna secesyjna.", grades: [7] },
  { quote: "Nie pytaj, co kraj może zrobić dla ciebie – zapytaj, co ty możesz zrobić dla kraju.", answer: "John F. Kennedy", context: "Inauguracja 1961.", grades: [8] },
  { quote: "I have a dream.", answer: "Martin Luther King", context: "Waszyngton 1963.", grades: [7, 8] },
  { quote: "Prawda was wyzwoli.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Wiele jest rzeczy wspaniałych, lecz nic nad człowieka.", answer: "Sofokles", context: "Antygona.", grades: [5] },
  { quote: "Poznaj samego siebie.", answer: "Tales z Miletu", context: "Napis w Delfach.", grades: [5] },
  { quote: "Wiedza to potęga.", answer: "Francis Bacon", context: "Filozof.", grades: [6] },
  { quote: "Cogito ergo sum.", answer: "Kartezjusz", context: "Myślę, więc jestem.", grades: [6] },
  { quote: "Królestwo moje nie jest z tego świata.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Nie samym chlebem żyje człowiek.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Miłuj bliźniego swego jak siebie samego.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Oto człowiek.", answer: "Piłat", context: "Ecce homo – o Jezusie.", grades: [5] },
  { quote: "Nie pozwalam!", answer: "Tadeusz Rejtan", context: "Sejm rozbiorowy.", grades: [6] },
  { quote: "Wolność, wasza mość, to skarb.", answer: "Jan Zamoyski", context: "Do króla.", grades: [4, 6] },
  { quote: "Do broni! Ludu Warszawy!", answer: "Tadeusz Kościuszko", context: "Insurekcja 1794.", grades: [4, 6] },
  { quote: "Naszą ojczyznę zaczynamy!", answer: "Piotr Wysocki", context: "Noc listopadowa 1830.", grades: [7] },
  { quote: "Zemsta, zemsta na wroga!", answer: "Adam Mickiewicz", context: "Dziady.", grades: [7] },
  { quote: "O, gdybym kiedy dożył tej pociechy.", answer: "Adam Mickiewicz", context: "Pan Tadeusz.", grades: [7] },
  { quote: "Polsko, nie jesteś ty już niewolnicą!", answer: "Adam Mickiewicz", context: "Dziady.", grades: [7] },
  { quote: "Nie rzucim ziemi, skąd nasz ród.", answer: "Maria Konopnicka", context: "Rota.", grades: [4, 7] },
  { quote: "Ku pokrzepieniu serc pisałem.", answer: "Henryk Sienkiewicz", context: "O Trylogii.", grades: [4, 7] },
  { quote: "Quo vadis, Domine?", answer: "Św. Piotr", context: "Dokąd idziesz, Panie? – według legendy.", grades: [5, 7] },
  { quote: "Polska to wielka rzecz.", answer: "Józef Piłsudski", context: "O niepodległości.", grades: [4, 7, 8] },
  { quote: "Być zwyciężonym i nie ulec – to zwycięstwo.", answer: "Józef Piłsudski", context: "Myśli.", grades: [7, 8] },
  { quote: "Niepodległość nie jest dana raz na zawsze.", answer: "Józef Piłsudski", context: "XX w.", grades: [8] },
  { quote: "Polska jest jak obwarzanek – wartościowe są tylko kresy.", answer: "Roman Dmowski", context: "O granicach.", grades: [7] },
  { quote: "Nie ma niepodległości bez niepodległości ekonomicznej.", answer: "Eugeniusz Kwiatkowski", context: "Gdynia, COP.", grades: [4, 8] },
  { quote: "Budujmy Gdynię – okno na świat.", answer: "Eugeniusz Kwiatkowski", context: "II RP.", grades: [4, 8] },
  { quote: "Nie bójcie się – otwórzcie drzwi Chrystusowi.", answer: "Jan Paweł II", context: "Inauguracja pontyfikatu.", grades: [8] },
  { quote: "Wy jesteście przyszłością świata.", answer: "Jan Paweł II", context: "Do młodzieży.", grades: [8] },
  { quote: "Odwagi, nie lękajcie się.", answer: "Jan Paweł II", context: "Homilie.", grades: [8] },
  { quote: "Przebaczcie i proście o przebaczenie.", answer: "Jan Paweł II", context: "List do biskupów.", grades: [8] },
  { quote: "Praca u podstaw.", answer: "Aleksander Świętochowski", context: "Pozytywizm.", grades: [7] },
  { quote: "Bóg się rodzi, moc truchleje.", answer: "Franciszek Karpiński", context: "Kolęda.", grades: [4, 7] },
  { quote: "Wszyscy ludzie rodzą się wolni i równi w prawach.", answer: "Deklaracja praw człowieka i obywatela", context: "Rewolucja francuska 1789.", grades: [6] },
  { quote: "Wesele – a to Polska właśnie.", answer: "Stanisław Wyspiański", context: "Wesele.", grades: [7] },
  { quote: "Róbmy swoje.", answer: "Stanisław Wyspiański", context: "Wesele.", grades: [7] },
  { quote: "Smutno mi, Boże.", answer: "Juliusz Słowacki", context: "Hymn.", grades: [7] },
  { quote: "Ojczyzna to wspólny język i wspólna sprawa.", answer: "Adam Mickiewicz", context: "Księgi narodu polskiego.", grades: [7] },
  { quote: "Tear down this wall!", answer: "Ronald Reagan", context: "Berlin 1987.", grades: [8] },
  { quote: "Europa od Atlantyku po Ural.", answer: "Charles de Gaulle", context: "Wizja Europy.", grades: [8] },
  { quote: "Rewolucja pożera własne dzieci.", answer: "Georges Danton", context: "Rewolucja francuska.", grades: [6] },
  { quote: "Państwo to ja – L'État c'est moi.", answer: "Ludwik XIV", context: "Król Francji.", grades: [6] },
  { quote: "Alea iacta est.", answer: "Juliusz Cezar", context: "Kostka została rzucona.", grades: [5] },
  { quote: "Et tu, Brute?", answer: "Juliusz Cezar", context: "I ty, Brutusie? – według Szekspira.", grades: [5] },
  { quote: "Nie będę bił w braci – rozdzielam ziemie.", answer: "Bolesław Krzywousty", context: "Testament 1138.", grades: [5] },
  { quote: "Bogurodzica, Dziewica.", answer: "anonim (Bogurodzica)", context: "Pieśń rycerzy pod Grunwaldem.", grades: [4, 5] },
  { quote: "Król panuje, ale nie rządzi.", answer: "Jan Zamoyski", context: "Zasada Rzeczypospolitej.", grades: [6] },
  { quote: "Wiwat król, wiwat naród, wiwat wszystkie stany!", answer: "Konstytucja 3 maja", context: "1791.", grades: [4, 6] },
  { quote: "Wolność, całość, niepodległość.", answer: "Tadeusz Kościuszko", context: "Hasło insurekcji 1794.", grades: [4, 6] },
  { quote: "Naród sobą stanowi.", answer: "Konstytucja 3 maja", context: "Suwerenność narodu.", grades: [6] },
  { quote: "Honor i Ojczyzna.", answer: "Armia Krajowa", context: "Motto AK.", grades: [4, 8] },
  { quote: "Bóg, Honor, Ojczyzna.", answer: "Wojsko Polskie", context: "Motto.", grades: [4, 8] },
  { quote: "Prawdziwy Polak to ten, kto kocha ojczyznę.", answer: "Roman Dmowski", context: "Myśli nowoczesnego Polaka.", grades: [7] },
  { quote: "Msze za ojczyznę odprawiam.", answer: "Ks. Jerzy Popiełuszko", context: "Lata 80.", grades: [8] },
  { quote: "Świat musi być bezpieczny dla demokracji.", answer: "Woodrow Wilson", context: "I wojna światowa.", grades: [7] },
  { quote: "Krew i żelazo.", answer: "Otto von Bismarck", context: "Zjednoczenie Niemiec.", grades: [7] },
  { quote: "Wojna to piekło i nie pozwólcie nikomu mówić inaczej.", answer: "William Sherman", context: "Wojna secesyjna.", grades: [7] },
  { quote: "Ludzie rodzą się wolni i równi.", answer: "Jean-Jacques Rousseau", context: "Umowa społeczna.", grades: [6] },
  { quote: "Tu es Petrus – Ty jesteś Piotr.", answer: "Jezus Chrystus", context: "Ewangelia – do Piotra.", grades: [5] },
  { quote: "Oto człowiek – Ecce homo.", answer: "Piłat", context: "O Jezusie przed ukrzyżowaniem.", grades: [5] },
  { quote: "Nie ma nic w umyśle, czego wcześniej nie było w zmysłach.", answer: "John Locke", context: "Filozof.", grades: [6] },
  { quote: "Wystarczy, że ludzie dobrzy nic nie robią.", answer: "Edmund Burke", context: "O złu.", grades: [7] },
  { quote: "Rządzić to przewidywać.", answer: "Émile de Girardin", context: "XIX w.", grades: [7] },
  { quote: "Demokracja to rządy ludu, przez lud, dla ludu.", answer: "Abraham Lincoln", context: "Gettysburg.", grades: [6, 7] },
  { quote: "Ja jestem państwo.", answer: "Ludwik XIV", context: "Król Francji.", grades: [6] },
  { quote: "W imię prawa.", answer: "Maximilien Robespierre", context: "Rewolucja francuska.", grades: [6] },
  { quote: "Oświecenie to wyjście człowieka z niepełnoletności.", answer: "Immanuel Kant", context: "Filozof.", grades: [6] },
  { quote: "Wolność jednego kończy się tam, gdzie zaczyna wolność drugiego.", answer: "John Stuart Mill", context: "Filozof.", grades: [7] },
  { quote: "Nie ma drogi do pokoju; pokój jest drogą.", answer: "Mahatma Gandhi", context: "XX w.", grades: [8] },
  { quote: "Jedyny sposób, by zrobić wielką robotę, to kochać to, co się robi.", answer: "Steve Jobs", context: "XX w.", grades: [8] },
  { quote: "Prawdziwa podróż odkrywcza nie polega na szukaniu nowych lądów.", answer: "Marcel Proust", context: "Pisarz.", grades: [8] },
  { quote: "Jak kamienie przez Boga rzucane na szaniec.", answer: "Juliusz Słowacki", context: "Wiersz – tytuł „Kamieni na szaniec”.", grades: [4, 8] },
  { quote: "Wolność polega na tym, by robić to, co się chce.", answer: "Wolter", context: "Oświecenie.", grades: [6] },
  { quote: "Człowiek jest skazany na wolność.", answer: "Jean-Paul Sartre", context: "Egzystencjalizm.", grades: [8] },
  { quote: "Wiedza to potęga, a ignorancja to słabość.", answer: "Francis Bacon", context: "Filozof.", grades: [6] },
  { quote: "Nie ma nic bardziej praktycznego niż dobra teoria.", answer: "Kurt Lewin", context: "Psycholog.", grades: [8] },
  { quote: "Historia jest świadkiem czasów.", answer: "Cyceron", context: "Starożytny Rzym.", grades: [5] },
  { quote: "Kto nie zna historii, skazany jest na jej powtórzenie.", answer: "George Santayana", context: "Filozof.", grades: [7] },
  { quote: "W historii nie ma przypadków.", answer: "Lew Tołstoj", context: "Wojna i pokój.", grades: [7] },
  { quote: "Naród, który nie zna swej historii, skazany jest na jej powtórzenie.", answer: "Józef Piłsudski", context: "O znaczeniu historii.", grades: [7, 8] },
  { quote: "Polska to wielka rzecz – wielka i święta.", answer: "Józef Piłsudski", context: "O niepodległości.", grades: [4, 7, 8] },
  { quote: "Niepodległość jest dobrem nie tylko cennym, ale i kosztownym.", answer: "Józef Piłsudski", context: "XX w.", grades: [8] },
  { quote: "Warto być uczciwym, choć nie zawsze się to opłaca.", answer: "Władysław Bartoszewski", context: "Polityk, historyk.", grades: [8] },
  { quote: "Prawda was wyzwoli – Veritas liberabit vos.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Miłość i prawda spotykają się.", answer: "Jan Paweł II", context: "Encyklika.", grades: [8] },
  { quote: "Nie lękajcie się – otwórzcie drzwi Chrystusowi.", answer: "Jan Paweł II", context: "Inauguracja pontyfikatu.", grades: [8] },
  { quote: "Człowiek jest wielki nie przez to, co ma, lecz przez to, kim jest.", answer: "Jan Paweł II", context: "Homilie.", grades: [8] },
  { quote: "Wolność nie polega na robieniu tego, co się chce.", answer: "Jan Paweł II", context: "O wolności.", grades: [8] },
  { quote: "Solidarność to znaczy: jeden i drugi.", answer: "Jan Paweł II", context: "Encyklika.", grades: [8] },
  { quote: "Nie ma solidarności bez miłości.", answer: "Jan Paweł II", context: "Homilie.", grades: [8] },
  { quote: "Zwycięstwo przyjdzie przez Maryję.", answer: "Stefan kardynał Wyszyński", context: "Prymas Polski.", grades: [8] },
  { quote: "Non possumus – nie możemy.", answer: "Stefan Wyszyński", context: "Odpowiedź władzom komunistycznym.", grades: [8] },
  { quote: "Jestem z was, pamiętam o was, modlę się za was.", answer: "Jan Paweł II", context: "Do Polaków.", grades: [8] },
  { quote: "Człowiek jest stworzony do wolności.", answer: "Jan Paweł II", context: "Encyklika.", grades: [8] },
  { quote: "Marsz, marsz Dąbrowski, z ziemi włoskiej do Polski.", answer: "Józef Wybicki", context: "Mazurek Dąbrowskiego.", grades: [4, 6] },
  { quote: "Jak długo na Wawelu nie będzie Niemca.", answer: "Józef Piłsudski", context: "O niepodległości.", grades: [4, 7, 8] },
  { quote: "Kościuszko był wielkim człowiekiem.", answer: "Thomas Jefferson", context: "O Kościuszce.", grades: [4, 6] },
  { quote: "Wolność, równość, braterstwo albo śmierć.", answer: "Maximilien Robespierre", context: "Rewolucja francuska.", grades: [6] },
  { quote: "O, mój Boże, czy to możliwe?", answer: "Maria Skłodowska-Curie", context: "Po odkryciu radu.", grades: [4, 7] },
  { quote: "W nauce nie ma narodowości.", answer: "Maria Skłodowska-Curie", context: "Noblistka.", grades: [4, 7] },
  { quote: "Uczcie się pilnie, służcie wiernie.", answer: "Jan Paweł II", context: "Do młodzieży.", grades: [4, 8] },
  { quote: "Nie daj się zwyciężyć złu, ale zło dobrem zwyciężaj.", answer: "Św. Paweł", context: "List do Rzymian.", grades: [5] },
  { quote: "Cóż bowiem za korzyść odniesie człowiek, jeśli cały świat zyska.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Pozwólcie dzieciom przychodzić do Mnie.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Nie sądźcie, abyście nie byli sądzeni.", answer: "Jezus Chrystus", context: "Ewangelia.", grades: [5] },
  { quote: "Życie bez badania nie jest warte życia.", answer: "Sokrates", context: "Starożytna Grecja.", grades: [5] },
  { quote: "Wiem, że nic nie wiem – i to właśnie odróżnia mnie od innych.", answer: "Sokrates", context: "Starożytna Grecja.", grades: [5] },
  { quote: "Człowiek jest miarą wszechrzeczy.", answer: "Protagoras", context: "Starożytna Grecja.", grades: [5] },
  { quote: "Nic nad człowieka.", answer: "Sofokles", context: "Antygona.", grades: [5] },
  { quote: "Nie ma nic trwałego poza zmianą.", answer: "Heraklit", context: "Starożytna Grecja.", grades: [5] },
  { quote: "Wszystko płynie.", answer: "Heraklit", context: "Starożytna Grecja.", grades: [5] },
  { quote: "Wojna jest ojcem wszystkich rzeczy.", answer: "Heraklit", context: "Starożytna Grecja.", grades: [5] },
  { quote: "Platon jest mi drogi, lecz droższa prawda.", answer: "Arystoteles", context: "O Platonie.", grades: [5] },
  { quote: "Człowiek jest zwierzęciem politycznym.", answer: "Arystoteles", context: "Polityka.", grades: [5] },
  { quote: "Przyjaciel to drugi ja.", answer: "Arystoteles", context: "Etyka.", grades: [5] },
  { quote: "Nie ma w umyśle niczego, czego wcześniej nie było w zmysłach.", answer: "Arystoteles", context: "Filozof.", grades: [5] },
  { quote: "Dajcie mi wystarczająco długą dźwignię.", answer: "Archimedes", context: "O dźwigni.", grades: [5] },
  { quote: "Eureka!", answer: "Archimedes", context: "Po odkryciu prawa wyporu.", grades: [5] },
  { quote: "Przekroczyłem Alpy.", answer: "Hannibal", context: "Wojny punickie.", grades: [5] },
  { quote: "Aleksander płacze – nie ma już światów do zdobycia.", answer: "Aleksander Macedoński", context: "Według przekazów.", grades: [5] },
  { quote: "Nie boję się armii lwów, gdy prowadzi je owca.", answer: "Aleksander Macedoński", context: "O Persach.", grades: [5] },
  { quote: "Przyjaciele, oto koniec.", answer: "Juliusz Cezar", context: "Przed śmiercią.", grades: [5] },
  { quote: "I ty, Brutusie, przeciw mnie?", answer: "Juliusz Cezar", context: "Idy marcowe.", grades: [5] },
  { quote: "Lepiej być pierwszym w małym mieście niż drugim w Rzymie.", answer: "Juliusz Cezar", context: "Młodzieńcze marzenia.", grades: [5] },
  { quote: "Przybyłem, zobaczyłem, zwyciężyłem.", answer: "Juliusz Cezar", context: "Veni, vidi, vici.", grades: [5] },
  { quote: "Róbmy, co robimy – z miłości do ojczyzny.", answer: "Tadeusz Kościuszko", context: "Insurekcja.", grades: [4, 6] },
  { quote: "Wolność całej ludzkości jest celem.", answer: "Tadeusz Kościuszko", context: "USA i Polska.", grades: [4, 6] },
  { quote: "Za naszą i waszą wolność.", answer: "Powstańcy listopadowi", context: "Hasło powstania.", grades: [7] },
  { quote: "Polska jeszcze nie zginęła.", answer: "Józef Wybicki", context: "Pieśń Legionów.", grades: [4, 6] },
  { quote: "Ojczyzna to wielka rzecz.", answer: "Józef Piłsudski", context: "O Polsce.", grades: [4, 7, 8] },
  { quote: "Kto nie szanuje historii, nie jest wart wolności.", answer: "Józef Piłsudski", context: "O historii.", grades: [7, 8] },
  { quote: "Być zwyciężonym i nie ulec – zwycięstwo.", answer: "Józef Piłsudski", context: "Myśli.", grades: [4, 7, 8] },
  { quote: "Niepodległość jest dobrem cennym.", answer: "Józef Piłsudski", context: "XX w.", grades: [8] },
  { quote: "Tu się bijemy i tu się bronimy.", answer: "Augustyn Kordecki", context: "Jasna Góra.", grades: [4, 6] },
  { quote: "Wolność, wasza mość, to skarb Rzeczypospolitej.", answer: "Jan Zamoyski", context: "Do króla.", grades: [4, 6] },
  { quote: "Nie pozwalam – liberum veto.", answer: "Tadeusz Rejtan", context: "Sejm rozbiorowy.", grades: [6] },
  { quote: "Rzeczpospolita jest jak stół – każdy ma równe prawo.", answer: "Szlachta polska", context: "Złota wolność.", grades: [6] },
  { quote: "Za króla Sasa jedz, pij i popuszczaj pasa.", answer: "Szlachta", context: "Czasy saskie.", grades: [6] },
  { quote: "Marysieńka, serce me.", answer: "Jan III Sobieski", context: "Listy do żony.", grades: [4, 6] },
  { quote: "Wiwat król, wiwat naród!", answer: "Ustawa 3 maja", context: "1791.", grades: [4, 6] },
  { quote: "Naród sobą stanowi – suwerenność.", answer: "Konstytucja 3 maja", context: "1791.", grades: [6] },
  { quote: "Litwo! Ojczyzno moja!", answer: "Adam Mickiewicz", context: "Pan Tadeusz.", grades: [7] },
  { quote: "Miej serce i patrz w serce.", answer: "Adam Mickiewicz", context: "Dziady.", grades: [7] },
  { quote: "O, gdybym kiedy dożył tej pociechy.", answer: "Adam Mickiewicz", context: "Pan Tadeusz.", grades: [7] },
  { quote: "Zemsta, zemsta na wroga – z Bogiem!", answer: "Adam Mickiewicz", context: "Dziady.", grades: [7] },
  { quote: "Ku pokrzepieniu serc pisałem.", answer: "Henryk Sienkiewicz", context: "O Trylogii.", grades: [4, 7] },
  { quote: "Nie rzucim ziemi, skąd nasz ród.", answer: "Maria Konopnicka", context: "Rota.", grades: [4, 7] },
  { quote: "Quo vadis, Domine?", answer: "Św. Piotr", context: "Dokąd idziesz, Panie?", grades: [5, 7] },
  { quote: "Bóg się rodzi, moc truchleje.", answer: "Franciszek Karpiński", context: "Kolęda.", grades: [4, 7] },
  { quote: "Praca u podstaw – hasło.", answer: "Aleksander Świętochowski", context: "Pozytywizm.", grades: [7] },
  { quote: "Ojczyzna to wielki zbiorowy obowiązek.", answer: "Cyprian Kamil Norwid", context: "XIX w.", grades: [7] },
  { quote: "Naród, który traci pamięć, traci sumienie.", answer: "Cyprian Kamil Norwid", context: "XIX w.", grades: [7] },
  { quote: "Róbmy swoje – każdy swe miejsce zna.", answer: "Stanisław Wyspiański", context: "Wesele.", grades: [7] },
  { quote: "Smutno mi, Boże – dla mnie.", answer: "Juliusz Słowacki", context: "Hymn.", grades: [7] },
  { quote: "Wolność wasza jest wolnością naszą.", answer: "Lech Wałęsa", context: "Kongres USA.", grades: [4, 8] },
  { quote: "Solidarność – jeden za wszystkich.", answer: "Lech Wałęsa", context: "NSZZ.", grades: [4, 8] },
  { quote: "Nie ma wolności bez Solidarności.", answer: "Lech Wałęsa", context: "Lata 80.", grades: [8] },
  { quote: "Żeby Polska była Polską.", answer: "Jan Pietrzak", context: "Piosenka.", grades: [8] },
  { quote: "Pomożecie? – do robotników.", answer: "Edward Gierek", context: "1971.", grades: [8] },
  { quote: "Nie ma lekko – trzeba pracować.", answer: "Edward Gierek", context: "PRL.", grades: [8] },
  { quote: "Żądamy chleba i wolności.", answer: "Robotnicy Poznania", context: "1956.", grades: [8] },
  { quote: "Kto nie był w Warszawie w czasie powstania.", answer: "Tadeusz Bór-Komorowski", context: "Powstanie warszawskie.", grades: [8] },
  { quote: "Zginę za Polskę – ostatnie słowa.", answer: "Witold Pilecki", context: "Przed egzekucją.", grades: [4, 8] },
  { quote: "Żołnierz polski walczy o wolność wielu narodów.", answer: "Władysław Sikorski", context: "II wojna.", grades: [8] },
  { quote: "Nigdy w dziejach tak wielu nie zawdzięczało tak wiele tak nielicznym.", answer: "Winston Churchill", context: "Bitwa o Anglię.", grades: [8] },
  { quote: "To jest ich najwspanialsza godzina.", answer: "Winston Churchill", context: "II wojna.", grades: [8] },
  { quote: "Od Szczecina po Triest opadła żelazna kurtyna.", answer: "Winston Churchill", context: "Fulton 1946.", grades: [8] },
  { quote: "Jedna śmierć to tragedia, milion to statystyka.", answer: "Józef Stalin", context: "Przypisywane.", grades: [8] },
  { quote: "Give me liberty or give me death.", answer: "Patrick Henry", context: "USA.", grades: [6] },
  { quote: "Pokój za wszelką cenę.", answer: "Neville Chamberlain", context: "Przed II wojną.", grades: [8] },
  { quote: "I have a dream.", answer: "Martin Luther King", context: "Waszyngton 1963.", grades: [7, 8] },
  { quote: "Nie pytaj, co kraj może zrobić dla ciebie.", answer: "John F. Kennedy", context: "Inauguracja.", grades: [8] },
  { quote: "Tear down this wall!", answer: "Ronald Reagan", context: "Berlin.", grades: [8] },
  { quote: "Glasnost i pieriestrojka.", answer: "Michaił Gorbaczow", context: "ZSRR.", grades: [8] },
  { quote: "Wiedza to potęga.", answer: "Francis Bacon", context: "Filozof.", grades: [6] },
  { quote: "Cogito ergo sum – myślę, więc jestem.", answer: "Kartezjusz", context: "Filozof.", grades: [6] },
  { quote: "Człowiek rodzi się wolny.", answer: "Jean-Jacques Rousseau", context: "Umowa społeczna.", grades: [6] },
  { quote: "Władza deprawuje, władza absolutna deprawuje absolutnie.", answer: "Lord Acton", context: "XIX w.", grades: [7] },
  { quote: "Proletariusze wszystkich krajów, łączcie się!", answer: "Karol Marx", context: "Manifest komunistyczny.", grades: [7] },
  { quote: "Wojna to kontynuacja polityki innymi środkami.", answer: "Carl von Clausewitz", context: "XIX w.", grades: [7] },
  { quote: "Żelazem i krwią – Bismarck.", answer: "Otto von Bismarck", context: "Zjednoczenie Niemiec.", grades: [7] },
  { quote: "Świat musi być bezpieczny dla demokracji.", answer: "Woodrow Wilson", context: "I wojna.", grades: [7] },
  { quote: "Polacy nie gęsi, swój język mają.", answer: "Mikołaj Rej", context: "Renesans.", grades: [5, 6] },
  { quote: "Wstrzymał Słońce, ruszył Ziemię – o Koperniku.", answer: "Jan Kochanowski", context: "Tren.", grades: [5, 6] },
  { quote: "Tu się bijemy, tu się bronimy – Jasna Góra.", answer: "Augustyn Kordecki", context: "Potop.", grades: [4, 6] },
  { quote: "Nie ma niepodległości bez niepodległości ekonomicznej.", answer: "Eugeniusz Kwiatkowski", context: "Gdynia.", grades: [4, 8] },
  { quote: "Budujmy Gdynię – okno na świat.", answer: "Eugeniusz Kwiatkowski", context: "II RP.", grades: [4, 8] },
  { quote: "Nie ma sprawy ważniejszej niż Polska.", answer: "Wincenty Witos", context: "Premier.", grades: [7, 8] },
  { quote: "Honor i Ojczyzna – motto AK.", answer: "Armia Krajowa", context: "II wojna.", grades: [4, 8] },
  { quote: "Bóg, Honor, Ojczyzna.", answer: "Wojsko Polskie", context: "Motto.", grades: [4, 8] },
];

/** Normalizacja do porównań (małe litery, bez polskich znaków). */
function normalizeForCompare(s) {
  if (!s || typeof s !== "string") return "";
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/** Sprawdza, czy odpowiedź jest zawarta w cytacie (odpowiedź w pytaniu / opis "X – Y"). */
function isAnswerContainedInQuote(quote, answer) {
  const q = normalizeForCompare(quote);
  const a = normalizeForCompare(answer);
  if (!a) return false;
  if (q.includes(a)) return true;
  const parts = a.split(/\s+/).filter(Boolean);
  const lastName = parts[parts.length - 1];
  if (lastName && lastName.length > 2 && q.includes(lastName)) return true;
  const beforeDash = quote.split(/[–-]/)[0].trim();
  if (normalizeForCompare(beforeDash) === a) return true;
  if (beforeDash.length < 25 && normalizeForCompare(beforeDash) === normalizeForCompare(parts[0])) return true;
  return false;
}

const filtered = quotes.filter((item) => {
  const bad = isAnswerContainedInQuote(item.quote, item.answer);
  if (bad) console.warn("Pominięto (odpowiedź w pytaniu / nie-cytat):", item.quote.slice(0, 50) + "...", "→", item.answer);
  return !bad;
});

const final = filtered;

function countByGrade(items) {
  const c = { 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 };
  items.forEach((item) => {
    (item.grades || []).forEach((g) => {
      if (c[g] !== undefined) c[g]++;
    });
  });
  return c;
}

const counts = countByGrade(final);
console.log("Cytaty per klasa:", counts);
console.log("Łącznie wpisów:", final.length);

fs.writeFileSync(
  path.join(__dirname, "../lib/data/quotes.json"),
  JSON.stringify(final, null, 2),
  "utf8"
);
